"""Pydantic models for ACS Image Integrations."""

from typing import Optional, List
from pydantic import BaseModel


class DockerConfig(BaseModel):
    """Docker registry configuration."""
    endpoint: str
    username: Optional[str] = None
    password: Optional[str] = None
    insecure: bool = False


class QuayConfig(BaseModel):
    """Quay registry configuration."""
    endpoint: str
    oauth_token: Optional[str] = None
    insecure: bool = False


class GcrConfig(BaseModel):
    """Google Container Registry configuration."""
    endpoint: str = "gcr.io"
    service_account: str


class EcrConfig(BaseModel):
    """Amazon ECR configuration."""
    region: str
    access_key_id: Optional[str] = None
    secret_access_key: Optional[str] = None
    use_iam: bool = True
    endpoint: Optional[str] = None


class AcrConfig(BaseModel):
    """Azure Container Registry configuration."""
    endpoint: str
    username: Optional[str] = None
    password: Optional[str] = None


class ArtifactoryConfig(BaseModel):
    """JFrog Artifactory configuration."""
    endpoint: str
    username: str
    password: str


class NexusConfig(BaseModel):
    """Nexus Repository configuration."""
    endpoint: str
    username: str
    password: str


class ImageIntegration(BaseModel):
    """ACS Image Integration model."""
    id: Optional[str] = None
    name: str
    type: str  # docker, quay, gcr, ecr, acr, artifactory, nexus, rhel, google, clair, clairify

    # Categories: REGISTRY, SCANNER, NODE_SCANNER
    categories: List[str] = ["REGISTRY"]

    # Auto-generated flag
    autogenerated: bool = False

    # Cluster-specific integration
    cluster_id: Optional[str] = None

    # Skip test on create
    skip_test_integration: bool = False

    # Type-specific configs
    docker: Optional[DockerConfig] = None
    quay: Optional[QuayConfig] = None
    gcr: Optional[GcrConfig] = None
    ecr: Optional[EcrConfig] = None
    acr: Optional[AcrConfig] = None
    artifactory: Optional[ArtifactoryConfig] = None
    nexus: Optional[NexusConfig] = None

    class Config:
        extra = "allow"

    def to_api_payload(self) -> dict:
        """Convert to ACS API payload format."""
        payload = {
            "name": self.name,
            "type": self.type,
            "categories": self.categories,
            "autogenerated": self.autogenerated,
            "skipTestIntegration": self.skip_test_integration,
        }

        if self.id:
            payload["id"] = self.id

        if self.cluster_id:
            payload["clusterId"] = self.cluster_id

        if self.type == "docker" and self.docker:
            payload["docker"] = {
                "endpoint": self.docker.endpoint,
                "insecure": self.docker.insecure,
            }
            if self.docker.username:
                payload["docker"]["username"] = self.docker.username
            if self.docker.password:
                payload["docker"]["password"] = self.docker.password

        elif self.type == "quay" and self.quay:
            payload["quay"] = {
                "endpoint": self.quay.endpoint,
                "insecure": self.quay.insecure,
            }
            if self.quay.oauth_token:
                payload["quay"]["oauthToken"] = self.quay.oauth_token

        elif self.type == "gcr" and self.gcr:
            payload["gcr"] = {
                "endpoint": self.gcr.endpoint,
                "serviceAccount": self.gcr.service_account,
            }

        elif self.type == "ecr" and self.ecr:
            payload["ecr"] = {
                "region": self.ecr.region,
                "useIam": self.ecr.use_iam,
            }
            if self.ecr.access_key_id:
                payload["ecr"]["accessKeyId"] = self.ecr.access_key_id
            if self.ecr.secret_access_key:
                payload["ecr"]["secretAccessKey"] = self.ecr.secret_access_key
            if self.ecr.endpoint:
                payload["ecr"]["endpoint"] = self.ecr.endpoint

        elif self.type == "artifactory" and self.artifactory:
            payload["docker"] = {
                "endpoint": self.artifactory.endpoint,
                "username": self.artifactory.username,
                "password": self.artifactory.password,
            }

        return payload
